{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-deployment.serviceAccountName" . }}
  labels:
{{ include "kube-deployment.labels" . | indent 4 }}
{{- end -}}
